### ISSUE TITLE
BSD mergesort is not portable

### ISSUE THREAD

**Issue by jeromekelleher** [richarddurbin/pbwt#35]
referenceImpute3 in pbwtImpute.c uses BSD mergesort which is not available in glibc. This makes it difficult to compile under linux. A direct replacement with qsort seems to work fine.

I don't think the performance consequences of this should be too bad. On glibc at least, qsort actually uses mergesort under the hood unless the array is very large. I'm not sure what the performance consequences would be on a mac though.

**Comment by richarddurbin** [comment]
Yes.  Several people have been bitten by this.  I should switch it, at least by default.

Thanks,

Richard

> On 17 Jul 2015, at 15:04, Jerome Kelleher <notifications@github.com> wrote:
> 
> referenceImpute3 in pbwtImpute.c uses BSD mergesort which is not available in glibc. This makes it difficult to compile under linux. A direct replacement with qsort seems to work fine.
> 
> I don't think the performance consequences of this should be too bad. On glibc at least, qsort actually uses mergesort under the hood unless the array is very large. I'm not sure what the performance consequences would be on a mac though.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/richarddurbin/pbwt/issues/35>.
> 




-- 
 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by wkretzsch** [comment]
I think I might be running into this issue as well?

When I run `make` on my fedora 21 machine, then I get the following error message:

    gcc -g -o pbwt pbwtMain.o pbwtCore.o pbwtSample.o pbwtIO.o pbwtMatch.o pbwtImpute.o pbwtPaint.o pbwtLikelihood.o pbwtMerge.o pbwtGeneticMap.o pbwtHtslib.o hash.o dict.o array.o utils.o ../htslib/libhts.a -lpthread -lz -lm
    pbwtImpute.o: In function `referenceImpute3':
    /homes/kretzsch/opt/pbwt/pbwtImpute.c:1148: undefined reference to `mergesort'
    collect2: error: ld returned 1 exit status
    makefile:28: recipe for target 'pbwt' failed
    make: *** [pbwt] Error 1

I am using htslib version `1.2.1-113-g826454f`.
Any ideas on how to work around this?

**Comment by jeromekelleher** [comment]
I just replaced mergesort with quicksort @wkretzsch and it worked fine. You'll need to remove the conditional check for errors as well, as quicksort doesn't return anything.

**Comment by johnlees** [comment]
see also https://github.com/richarddurbin/pbwt/issues/32

**Comment by wkretzsch** [comment]
I tried replacing mergesort with qsort in this commit wkretzsch/pbwt@7c539297dddef3c730362b7283255a03d5fee74f.  `make test` runs ok on my mac, but on fedora 21 five out of ten tests fail.  Looks like there may be more portability issues than just the mergesort?

**Comment by jeromekelleher** [comment]
@wkretzsch running ``make test`` on my Debian Jessie machine results in 5 failures also. I guess I should have checked this!

**Comment by richarddurbin** [comment]
This was fixed a while ago.  The default behaviour is to use qsort().  If you are on a platform that has mergesort() in its library and set environment variable MERGESORT then it will be used - I am not sure whether this is actually faster!
