### ISSUE TITLE
unable to build pbwt

### ISSUE THREAD

**Issue by pauline-ng** [richarddurbin/pbwt#44]
Hi,

I'm trying to compile pbwt and I'm getting this error

cc -g -O3 -I../htslib  -c -o pbwtMain.o pbwtMain.c
cc -g -O3 -I../htslib  -c -o pbwtCore.o pbwtCore.c
pbwtCore.c: In function ‘pbwtSelectSites’:
pbwtCore.c:684:97: error: ‘site’ undeclared (first use in this function)
 *pOld, Array sites, BOOL isKeepOld) { return pbwtSelectSites (pOld, site, isKee
                                                                     ^
pbwtCore.c:684:97: note: each undeclared identifier is reported only once for each function it appears in
pbwtCore.c:684:74: error: too many arguments to function ‘pbwtSelectSites’
 *pbwtSelectSites (PBWT *pOld, Array sites, BOOL isKeepOld) { return pbwtSelectS

pbwtCore.c:686:85: error: too many arguments to function ‘pbwtSelectSites’
 SitesFillMissing (PBWT *pOld, Array sites, BOOL isKeepOld) { return pbwtSelectS
                                                                     ^
pbwtCore.c:684:7: note: declared here
 PBWT *pbwtSelectSites (PBWT *pOld, Array sites, BOOL isKeepOld) { return pbwtSe
       ^
<builtin>: recipe for target 'pbwtCore.o' failed
make: *** [pbwtCore.o] Error 1
                                                                     ^
Thanks,
Pauline

**Comment by richarddurbin** [comment]
this is fixed now in the latest commit.
