### ISSUE TITLE
can't compile 

### ISSUE THREAD

**Issue by dauss75** [richarddurbin/pbwt#45]
Hello,

I am trying to install in ubuntu 14.04. While I was able to compile htslib, I failed pbwt with the following errors:

echo '#define PBWT_COMMIT_HASH "0811999"' > version.h
cc -g -O3 -I../htslib  -c -o pbwtMain.o pbwtMain.c
cc -g -O3 -I../htslib  -c -o pbwtCore.o pbwtCore.c
pbwtCore.c: In function ‘pbwtSelectSites’:
pbwtCore.c:684:97: error: ‘site’ undeclared (first use in this function)
 PBWT *pbwtSelectSites (PBWT *pOld, Array sites, BOOL isKeepOld) { return pbwtSelectSites (pOld, site, isKeepOld, FALSE) ; }
                                                                                                 ^
pbwtCore.c:684:97: note: each undeclared identifier is reported only once for each function it appears in
pbwtCore.c:684:1: error: too many arguments to function ‘pbwtSelectSites’
 PBWT *pbwtSelectSites (PBWT *pOld, Array sites, BOOL isKeepOld) { return pbwtSelectSites (pOld, site, isKeepOld, FALSE) ; }
 ^
pbwtCore.c:684:7: note: declared here
 PBWT *pbwtSelectSites (PBWT *pOld, Array sites, BOOL isKeepOld) { return pbwtSelectSites (pOld, site, isKeepOld, FALSE) ; }
       ^
pbwtCore.c: In function ‘pbwtSelectSitesFillMissing’:
pbwtCore.c:686:108: error: ‘site’ undeclared (first use in this function)
 PBWT *pbwtSelectSitesFillMissing (PBWT *pOld, Array sites, BOOL isKeepOld) { return pbwtSelectSites (pOld, site, isKeepOld, TRUE) ; }
                                                                                                            ^
pbwtCore.c:686:1: error: too many arguments to function ‘pbwtSelectSites’
 PBWT *pbwtSelectSitesFillMissing (PBWT *pOld, Array sites, BOOL isKeepOld) { return pbwtSelectSites (pOld, site, isKeepOld, TRUE) ; }
 ^
pbwtCore.c:684:7: note: declared here
 PBWT *pbwtSelectSites (PBWT *pOld, Array sites, BOOL isKeepOld) { return pbwtSelectSites (pOld, site, isKeepOld, FALSE) ; }
       ^
make: *** [pbwtCore.o] Error 1

Could you help me resolve this?

**Comment by mdkeehan** [comment]
I think this is a duplicate report from #44 

I replicate both of them on my machine : Ubuntu 12.04 

On a clean 
checkout, make clean, make 

If I checkout master at 15f7b1b I get a clean compile.
Looking carefully at the error message I think at least  "site" needs to be corrected to "sites"
plus a function name changed somewhere.

**Comment by Kparn** [comment]
I'm having the same error in unix server, any ideas how to get around it?

**Comment by amittos** [comment]
I also have the same problem. Any workarounds?

**Comment by richarddurbin** [comment]
I am looking into this.  (Easy to make it compile, but I want to make sure all is correct.)
Meanwhile https://github.com/VertebrateResequencing/pbwt has a compilable version that does all standard imputation reliably (this is the version used by the Sanger imputation service).

Thanks, Richard

**Comment by richarddurbin** [comment]
This is fixed now in the latest commit.
